route:
  receiver: 'Mail Alert'
  repeat_interval: 30s
  group_wait: 15s
  group_interval: 15s

receivers:
  - name: 'Mail Alert'
    email_configs:
      - smarthost: 'smtp.gmail.com:587'
        auth_username: "$EMAIL_USERNAME"
        auth_identity: "$EMAIL_USERNAME"
        auth_password: "$EMAIL_PASSWORD"
        from: $EMAIL_USERNAME
        to: $EMAIL_USERNAME
        headers:
          subject: 'Prometheus Mail Alerts'