global:
  scrape_interval: 15s
  evaluation_interval: 15s
  scrape_timeout: 10s

rule_files: 
  - alert.yml

alerting:
  alertmanagers:
    - scheme: http
      static_configs:
        - targets: [ "alertmanager:9093"]

scrape_configs:
  - job_name: "api"
    static_configs: 
      - targets: [ "app:3000" ]
