# Build from latest grafana image
FROM grafana/grafana:latest

# Copy config files
ADD ./provisioning /etc/grafana/provisioning
ADD ./config.ini /etc/grafana/config.ini
ADD ./dashboards /var/lib/grafana/dashboards
